from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 1000)
        MainWindow.setStyleSheet("background-color: rgb(248, 245, 223)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 20, 960, 960))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label_picture_tomat = QtWidgets.QLabel(self.frame)
        self.label_picture_tomat.setGeometry(QtCore.QRect(200, 160, 531, 611))
        self.label_picture_tomat.setText("")
        self.label_picture_tomat.setPixmap(QtGui.QPixmap(".//files//tomato.png"))
        self.label_picture_tomat.setScaledContents(True)
        self.label_picture_tomat.setObjectName("label_picture_tomat")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(130, 870, 721, 54))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.start_button = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.start_button.setFont(font)
        self.start_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.start_button.setMouseTracking(True)
        self.start_button.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.start_button.setCheckable(False)
        self.start_button.setObjectName("start_button")
        self.horizontalLayout.addWidget(self.start_button)
        self.labe_hackenl = QtWidgets.QLabel(self.layoutWidget)
        self.labe_hackenl.setMouseTracking(False)
        self.labe_hackenl.setAutoFillBackground(False)
        self.labe_hackenl.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.labe_hackenl.setObjectName("labe_hackenl")
        self.horizontalLayout.addWidget(self.labe_hackenl)
        self.reset_button = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.reset_button.setFont(font)
        self.reset_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.reset_button.setMouseTracking(True)
        self.reset_button.setStyleSheet("\n""background-color: rgb(255, 255, 255);")
        self.reset_button.setCheckable(False)
        self.reset_button.setObjectName("reset_button")
        self.horizontalLayout.addWidget(self.reset_button)
        self.label_Work_Rest = QtWidgets.QLabel(self.frame)
        self.label_Work_Rest.setGeometry(QtCore.QRect(280, 20, 400, 100))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(60)
        font.setBold(False)
        font.setWeight(50)
        self.label_Work_Rest.setFont(font)
        self.label_Work_Rest.setMouseTracking(False)
        self.label_Work_Rest.setLineWidth(1)
        self.label_Work_Rest.setScaledContents(False)
        self.label_Work_Rest.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_Work_Rest.setWordWrap(True)
        self.label_Work_Rest.setIndent(-2)
        self.label_Work_Rest.setObjectName("label_Work_Rest")
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setGeometry(QtCore.QRect(340, 630, 291, 71))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label_timer = QtWidgets.QLabel(self.frame)
        self.label_timer.setGeometry(QtCore.QRect(250, 440, 431, 141))
        self.label_timer.setStyleSheet("background-color: rgb(109, 109, 109);""color: rgb(0, 255, 127);""font: 75 60pt \"Verdana\";")
        self.label_timer.setAlignment(QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_timer.setObjectName("label_timer")
        self.label_date_now = QtWidgets.QLabel(self.frame)
        self.label_date_now.setGeometry(QtCore.QRect(300, 800, 360, 25))
        self.label_date_now.setStyleSheet("background-color: rgb(0, 255, 255);""font: 16pt \"MS Shell Dlg 2\";")
        self.label_date_now.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_date_now.setObjectName("label_date_now")
        self.label_color_right = QtWidgets.QLabel(self.frame)
        self.label_color_right.setGeometry(QtCore.QRect(860, 100, 50, 750))
        self.label_color_right.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.label_color_right.setText("")
        self.label_color_right.setObjectName("label_color_right")
        self.label_color_left = QtWidgets.QLabel(self.frame)
        self.label_color_left.setGeometry(QtCore.QRect(50, 100, 50, 750))
        self.label_color_left.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.label_color_left.setText("")
        self.label_color_left.setObjectName("label_color_left")
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
